### PR TITLE
added header font

### PR DESCRIPTION
**Pull request by ishan-nahid**
added header font suitable to me and also updated profile section

### CODE REVIEW

**Comment by tsongtheng** [comment]
Hey @ishan-nahid, thanks for the pull request 🙏.

Can you please add your profile image link of any social platform  in the `imageLink:` of the object you created  in the **`Profiles.js`**. The link you have added is my github profile link. You can add your github profile image link there.

**Comment by ishan-nahid** [comment]
can you edit the link and remove that?
i have no image to show now.

**Comment by tsongtheng** [comment]
> can you edit the link and remove that? i have no image to show now.

Ok

**Comment by ishan-nahid** [comment]
@tsongtheng 
this issue got EXCLUDED from hacktoberfest profile.
can you resolve it?

**Comment by tsongtheng** [comment]
hey @ishan-nahid, let me  check and I will get back to you.

**Comment by tsongtheng** [comment]
Hey @ishan-nahid, I don't know why it is  showing **EXCLUDED** . I have put the label to `hacktoberfest`. I have no idea on this.

**Comment by ishan-nahid** [comment]
it says "Your PR/MR was submitted to a repository that has been excluded from Hacktoberfest as it does not follow the values of the event. It will not count towards your participation. For more information about how exactly we validate PR/MRs for contributors, check the  details on our participation page https://hacktoberfest.com/participation/#pr-mr-details"

**Comment by tsongtheng** [comment]
Hello @ishan-nahid, may be I have not followed the rule of HACKTOBERFEST properly and if the ***message above*** is displayed in the HACKTOBERFEST website, then this repository is not eligible for hacktoberfest.

🙏 Sorry for wasting your time. You can checkout other repository and make **PR** there.

I appreciate, you have notified me early.

**Pull request merged**
