### PR TITLE
Changed the background image

### PR DESCRIPTION
**Pull request by fatimashaikh04**

### CODE REVIEW

**Review by tsongtheng — CHANGES_REQUESTED** [review]
Hey @fatimashaikh04 , can you please add **Image credit** in `README.md` file.
- Copy the image credit link from the website you have taken the  **background image** and paste it. (**Checkout the last line** of `README.md`)

**Comment by fatimashaikh04** [comment]
> Hey @fatimashaikh04 , can you please add **Image credit** in `README.md` file.
> 
> * Copy the image credit link from the website you have taken the  **background image** and paste it. (**Checkout the last line** of `README.md`)

suree

**Comment by tsongtheng** [comment]
Also update your `fork` and `clone` repository.

**Comment by fatimashaikh04** [comment]
done

**Review by tsongtheng — APPROVED** [review]

**Comment by tsongtheng** [comment]
Hey @fatimashaikh04 , 🙏 thanks for making a pull request  and contributing to [Add-Social-Profiles-Hacktoberfest2023](https://github.com/tsongtheng/Add-Social-Profiles-Hacktoberfest2023)

**Pull request merged**
